//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManageApp.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Gym_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gym_Client()
        {
            this.Gym_Payement = new HashSet<Gym_Payement>();
        }
    
        public int IdClient { get; set; }

        [Required(ErrorMessage = "Veuillez renseigner le Nom")]
        public string Nom { get; set; }

        [Display(Name = "Prénom")]
        [Required(ErrorMessage = "Veuillez renseigner le Prénom")]
        public string Prenom { get; set; }

        [Required(ErrorMessage = "Veuillez renseigner le numéro de CIN")]
        public string CIN { get; set; }

        [Display(Name = "Téléphone")]
        public string Telephone { get; set; }

        public string Email { get; set; }
        public Nullable<int> IdPayementEnCours { get; set; }
        public Nullable<bool> Actif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gym_Payement> Gym_Payement { get; set; }
    }
}
