//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManageApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gym_Payement
    {
        public int IdPayement { get; set; }
        public Nullable<int> IdClient { get; set; }
        public decimal Montant { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public System.DateTime DateProchainPayement { get; set; }
        public Nullable<bool> isWellOrdered { get; set; }
    
        public virtual Gym_Client Gym_Client { get; set; }
    }
}
