//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManageApp.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MedixTesttEntities : DbContext
    {
        public MedixTesttEntities()
            : base("name=MedixTesttEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<States> States { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<WorkOrders> WorkOrders { get; set; }
    
        public virtual ObjectResult<Sp_GetClients_Result> Sp_GetClients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetClients_Result>("Sp_GetClients");
        }
    
        public virtual ObjectResult<Sp_GetStates_Result> Sp_GetStates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetStates_Result>("Sp_GetStates");
        }
    
        public virtual ObjectResult<Sp_GetStatus_Result> Sp_GetStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetStatus_Result>("Sp_GetStatus");
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_GetWorkOrderCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_GetWorkOrderCount");
        }
    
        public virtual ObjectResult<Sp_GetWorkOrders_Result> Sp_GetWorkOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetWorkOrders_Result>("Sp_GetWorkOrders");
        }
    
        public virtual int Sp_InsertWorkOrder(string workOrderNumber, Nullable<int> clientId, Nullable<int> stateId, Nullable<int> statusId, Nullable<System.DateTime> eTA)
        {
            var workOrderNumberParameter = workOrderNumber != null ?
                new ObjectParameter("WorkOrderNumber", workOrderNumber) :
                new ObjectParameter("WorkOrderNumber", typeof(string));
    
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(int));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var eTAParameter = eTA.HasValue ?
                new ObjectParameter("ETA", eTA) :
                new ObjectParameter("ETA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_InsertWorkOrder", workOrderNumberParameter, clientIdParameter, stateIdParameter, statusIdParameter, eTAParameter);
        }
    }
}
